version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build 
      - tar -cvf nextjs-app.tar .

artifacts:
  files:
    - nextjs-app.tar 
    - appspec.yml 
    - deploy.sh  
  discard-paths: no

